version: '3'

services:
    # db:
    #     image: postgre:latest
    #     command: --default-authentication-plugin=mysql_native_password
    #     volumes:
    #         - "db_librarify:/var/lib/mysql"
    #     environment:
    #         PGSQL_ROOT_PASSWORD: ${PGSQL_ROOT_PASSWORD}
    #         PGSQL_DATABASE: ${PGSQL_DATABASE}
    #         PGSQL_USER: ${PGSQL_USER}
    #         PGSQL_PASSWORD: ${PGSQL_PASSWORD}
    #     ports:
    #         - 3306:3306
    #     networks:
    #         - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/librarify/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/librarify/
        ports:
            - 80:80
        networks:
            - symfony

# volumes:
#     db_librarify:

networks:
    symfony:
